### PR TITLE
Implemented asm_retf.

### PR DESCRIPTION
**Pull request by sindrom91**

### CODE REVIEW

**Comment by zhongweiy** [comment]
If you could add a test for IR_RETF, it would be helpful. I find this IR is not easy to emit.

**Comment by sindrom91** [comment]
There are some tests that produce IR_RETF in the LuaJIT testsuite:
https://github.com/LuaJIT/LuaJIT-test-cleanup/blob/master/test/trace/exit_frame.lua

I'm not sure if you want me to add these tests to our test suite or not. I haven't actually written any of my own tests that produce IR_RETF.

**Comment by zhongweiy** [comment]
Thanks for pointing out. Good to know it! I'm working on adding test cases now. I could help add that one to our test suite.

**Comment by sindrom91** [comment]
The thing is that those test files are often not so simple and contain tests that have a lot of side traces, which means that they produce quite a lot of different IRs. So I'm not sure how to go about this. Do you think we should just copy the whole files from that test suite or extract the tests that we need?

Also, in order to reproduce IR_RETF, I needed to fix asm_head_side_base and lj_asm_patchexit, because IR_RETF, apparently, is only produced in side-traces.

**Comment by zhongweiy** [comment]
I see. 
I think extract the tests that we need is better. But it may takes much more time. Anyway, I can also help add  it in later pull request.

**Pull request merged**
